#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-hoe
Version  : 3.15.1
Release  : 14
URL      : https://rubygems.org/downloads/hoe-3.15.1.gem
Source0  : https://rubygems.org/downloads/hoe-3.15.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-hoe-bin
BuildRequires : ruby
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
= Hoe
home  :: http://www.zenspider.com/projects/hoe.html
code  :: https://github.com/seattlerb/hoe
bugs  :: https://github.com/seattlerb/hoe/issues
rdoc  :: http://docs.seattlerb.org/hoe/
doco  :: http://docs.seattlerb.org/hoe/Hoe.pdf
other :: http://github.com/jbarnette/hoe-plugin-examples

%package bin
Summary: bin components for the rubygem-hoe package.
Group: Binaries

%description bin
bin components for the rubygem-hoe package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n hoe-3.15.1
gem spec %{SOURCE0} -l --ruby > rubygem-hoe.gemspec

%build
gem build rubygem-hoe.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
hoe-3.15.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/hoe-3.15.1
ruby -v -I.:lib:test test*/test_*.rb
ruby -v -I.:lib:test test*/*_test.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/hoe-3.15.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/.autotest
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/History.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/Hoe.pdf
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/Manifest.txt
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/bin/sow
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/lib/hoe.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/lib/hoe/clean.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/lib/hoe/compiler.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/lib/hoe/debug.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/lib/hoe/deps.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/lib/hoe/flay.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/lib/hoe/flog.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/lib/hoe/gem_prelude_sucks.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/lib/hoe/gemcutter.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/lib/hoe/inline.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/lib/hoe/newb.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/lib/hoe/package.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/lib/hoe/publish.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/lib/hoe/racc.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/lib/hoe/rake.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/lib/hoe/rcov.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/lib/hoe/rdoc.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/lib/hoe/signing.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/lib/hoe/test.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/template/.autotest.erb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/template/History.txt.erb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/template/Manifest.txt.erb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/template/README.txt.erb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/template/Rakefile.erb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/template/bin/file_name.erb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/template/lib/file_name.rb.erb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/template/test/test_file_name.rb.erb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/test/test_hoe.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/test/test_hoe_debug.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/test/test_hoe_gemcutter.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/test/test_hoe_package.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/test/test_hoe_publish.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-3.15.1/test/test_hoe_test.rb
/usr/lib64/ruby/gems/2.3.0/specifications/hoe-3.15.1.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/sow
